name: {{ cookiecutter.project_slug }}
channels:
  - conda-forge
  - defaults
dependencies:
  - python={{ cookiecutter.python_version }}
  - pip
  - pip:
    - pillow==10.2.0
    - matplotlib==3.8.2
    - scikit-learn==1.4.0
    - seaborn==0.13.1
    - numpy==1.23.0
    - tensorboard==2.15.1